version: '3'
services:
  market-data-worker:
    image: market-data-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python3 worker.py
    environment:
      - KAFKA_CONFIG=/kafka-config.yml
      - AWS_REGION=us-west-1
      - AWS_KEY=
      - AWS_SECRET=
      - BROKER_API_KEY=
      - INFLUXDB_URL=http://192.168.1.60:8086
      - APCA_API_BASE_URL=https://paper-api.alpaca.markets
      - APCA_API_KEY_ID=
      - APCA_API_SECRET_KEY=